workspace:
  base: /go
  path: src/github.com/drone/drone-cli

pipeline:
  test:
    image: golang:1.6
    commands:
      - cd drone
      - go test
  dist:
    image: golang:1.6
    commands: ./.drone.sh
    when:
      event: push

  # publish:
  #   image: s3
  #   when:
  #     event: push
  #     branch: master
