image: library/golang:1.4.1-cross

git:
  path: github.com/drone/drone-cli

env:
  - GOROOT=/usr/src/go
  - PATH=$PATH:$GOROOT/bin:$GOPATH/bin

script:
  - go get ./...
  - go test ./...
  - cd ./drone
  - GOOS=linux   GOARCH=amd64 go build -o ../dist/linux/amd64/drone
  - GOOS=linux   GOARCH=386   go build -o ../dist/linux/386/drone
  - GOOS=linux   GOARCH=arm   go build -o ../dist/linux/arm/drone
  - GOOS=darwin  GOARCH=amd64 go build -o ../dist/darwin/amd64/drone
  - GOOS=windows GOARCH=386   go build -o ../dist/windows/386/drone
  - GOOS=windows GOARCH=amd64 go build -o ../dist/windows/amd64/drone
  - apt-get update 1> /dev/null 2> /dev/null
  - apt-get -y install python-pip 1> /dev/null 2> /dev/null

notify:
  webhook:
    urls:
      - https://webhooks.gitter.im/e/$$GITTER_KEY
    on_started: false
    on_success: true
    on_failure: true

publish:
  s3:
    acl: public-read
    region: us-east-1
    bucket: downloads.drone.io
    access_key: $$AWS_KEY
    secret_key: $$AWS_SECRET
    source: dist/
    target: drone-cli/
    recursive: true
    when:
      branch: master
      owner: drone