workspace:
  base: /go
  path: src/github.com/drone/drone-cli

pipeline:
  test:
    image: golang:1.6
    commands:
      - cd drone
      - go test

  build:
    image: golang:1.6
    commands: bash .drone.sh
    when:
      event: push
